# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys


class Ui_window(object):
    def setupUi(self, window):
        window.setObjectName("window")
        window.resize(589, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(window.sizePolicy().hasHeightForWidth())
        window.setSizePolicy(sizePolicy)
        self.log = QtWidgets.QPlainTextEdit(window)
        self.log.setGeometry(QtCore.QRect(20, 40, 551, 211))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.log.sizePolicy().hasHeightForWidth())
        self.log.setSizePolicy(sizePolicy)
        self.log.setUndoRedoEnabled(False)
        self.log.setReadOnly(True)
        self.log.setObjectName("log")
        self.quit = QtWidgets.QPushButton(window)
        self.quit.setGeometry(QtCore.QRect(490, 260, 82, 25))
        self.quit.setObjectName("quit")
        self.log_label = QtWidgets.QLabel(window)
        self.log_label.setGeometry(QtCore.QRect(10, 20, 91, 16))
        self.log_label.setObjectName("log_label")

        self.retranslateUi(window)
        self.quit.clicked.connect(sys.exit) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(window)

    def retranslateUi(self, window):
        _translate = QtCore.QCoreApplication.translate
        window.setWindowTitle(_translate("window", "Crackpipe Auto Extractor"))
        self.quit.setText(_translate("window", "Quit"))
        self.log_label.setText(_translate("window", "Process Log:"))
